<?php

/**
 * HTML head.
 *
 * @author Dominik Harmim <harmim6@gmail.com>
 */

declare(strict_types=1);

use Main\Configuration;

?>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title><?= escape(Configuration::getTitle()); ?></title>

<meta name="description" content="<?= Configuration::getConfig('common', 'description'); ?>">
<meta name="author" content="DominikHarmim, harmim6@gmail.com">
<meta name="keywords" content="<?= Configuration::getConfig('common', 'keywords'); ?>">

<link rel="Shortcut icon" href="/images/icons/favicon.ico" type="image/x-icon">

<link rel="stylesheet" href="/css/bootstrap.min.css">
<link rel="stylesheet" href="/css/font-awesome.min.css">
<link rel="stylesheet" href="/css/dh/main.css">
